SELECT TOP (1000) [user_id]
      ,[tenant_id]
      ,[first_name]
      ,[middle_name]
      ,[last_name]
      ,[email]
      ,[password_hash]
      ,[status]
      ,[created_at]
      ,[profile_photo_url]
      ,[onboarding_complete]
      ,[role_type_name]
  FROM [dbo].[User_tbl]
